// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqf479yYHww4fToDlYs0jpoz94kEpy-DA',
    appId: '1:625994025513:web:5f93111cd7124ad0576a38',
    messagingSenderId: '625994025513',
    projectId: 'smd-project-e399c',
    authDomain: 'smd-project-e399c.firebaseapp.com',
    storageBucket: 'smd-project-e399c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc77paktAAFmndkhNKkrsj2HIVabO9AA0',
    appId: '1:625994025513:android:a16a4f818bc0546a576a38',
    messagingSenderId: '625994025513',
    projectId: 'smd-project-e399c',
    storageBucket: 'smd-project-e399c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo2OD7lCymwzuU50M9spPGNA7mV9Bl350',
    appId: '1:625994025513:ios:bd4ea3f276c92d16576a38',
    messagingSenderId: '625994025513',
    projectId: 'smd-project-e399c',
    storageBucket: 'smd-project-e399c.firebasestorage.app',
    iosBundleId: 'com.example.smdProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo2OD7lCymwzuU50M9spPGNA7mV9Bl350',
    appId: '1:625994025513:ios:bd4ea3f276c92d16576a38',
    messagingSenderId: '625994025513',
    projectId: 'smd-project-e399c',
    storageBucket: 'smd-project-e399c.firebasestorage.app',
    iosBundleId: 'com.example.smdProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqf479yYHww4fToDlYs0jpoz94kEpy-DA',
    appId: '1:625994025513:web:e9317c85bf1bcc33576a38',
    messagingSenderId: '625994025513',
    projectId: 'smd-project-e399c',
    authDomain: 'smd-project-e399c.firebaseapp.com',
    storageBucket: 'smd-project-e399c.firebasestorage.app',
  );
}
